plugins {
	id 'java'
	id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'com.jnditifei.connect.sink.saleforce'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenCentral()
}


dependencies {
	implementation 'org.apache.kafka:connect-api:3.9.0'
	implementation 'org.slf4j:slf4j-api:1.7.25'
	implementation 'com.squareup.okhttp3:logging-interceptor:3.14.2'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4.2'
	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
	testImplementation 'org.mockito:mockito-core:5.13.0'

}


tasks.named('shadowJar') {
	archiveBaseName.set('jnditifei-customBulkApiV2')
	archiveVersion.set('0.0.1-SNAPSHOT')
}

tasks.named('test') {
	useJUnitPlatform()
}


jar {
	manifest {
		attributes(
				'Plugin-Class': 'com.jnditifei.connect.sink.salesforce.BulkApiV2.SinkBulkApiV2Connector'
		)
	}
}